/* Broker / lender share email.
 * HTML mirrors docs/email-templates/broker-review.html.
 * Only sent when share.enabled && share.consent_confirmed.
 */

export const BROKER_SUBJECT = '{{first_name}} shared a Bank-Ready Score report for review';
export const BROKER_PREVIEW = 'A client-generated lending readiness summary for your review.';

export const BROKER_HTML = `<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{first_name}} shared a Bank-Ready Score report for review</title>
  </head>
  <body style="margin:0;padding:0;background:#f5f6f9;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;color:#0f172a;">
    <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#f5f6f9;padding:32px 16px;">
      <tr><td align="center">
        <table role="presentation" width="560" cellspacing="0" cellpadding="0" style="max-width:560px;background:#ffffff;border-radius:16px;overflow:hidden;border:1px solid #e5e7eb;">
          <tr><td style="padding:28px 28px 8px;">
            <p style="margin:0 0 8px;font-size:12px;letter-spacing:0.14em;text-transform:uppercase;color:#6b7280;font-weight:600;">Shared via Oney Bank-Ready Score</p>
            <h1 style="margin:0 0 12px;font-size:20px;line-height:1.3;color:#0f172a;">
              Hi {{recipient_name}}, {{first_name}} has shared their Bank-Ready Score report with you for review.
            </h1>
            <p style="margin:0 0 16px;font-size:14px;line-height:1.55;color:#334155;">
              The report was generated by {{first_name}}{{#business_name}} ({{business_name}}){{/business_name}} from their own answers. It's a readiness signal from a banker-built tool — <strong>not credit approval and not a formal recommendation</strong>.
            </p>
          </td></tr>

          <tr><td style="padding:8px 28px 16px;">
            <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#f1f5f9;border:1px solid #e2e8f0;border-radius:12px;">
              <tr><td style="padding:18px 20px;">
                <p style="margin:0 0 6px;font-size:12px;letter-spacing:0.1em;text-transform:uppercase;color:#475569;font-weight:600;">Summary</p>
                <p style="margin:0 0 4px;font-size:24px;font-weight:700;color:#0f172a;">{{score}} / 100 · {{score_band}}</p>
                <p style="margin:0 0 6px;font-size:13px;color:#475569;">Recommended path: <strong>{{recommended_path}}</strong></p>
                <p style="margin:0;font-size:13px;color:#475569;">{{profile_summary}}</p>
              </td></tr>
            </table>
          </td></tr>

          <tr><td style="padding:8px 28px 8px;">
            <h2 style="margin:12px 0 8px;font-size:15px;color:#0f172a;">Top actions currently highlighted</h2>
            <ol style="margin:0 0 8px 18px;padding:0;font-size:14px;line-height:1.55;color:#334155;">
              <li style="margin-bottom:8px;">{{top_action_1}}</li>
              <li style="margin-bottom:8px;">{{top_action_2}}</li>
              <li style="margin-bottom:8px;">{{top_action_3}}</li>
            </ol>
          </td></tr>

          <tr><td style="padding:8px 28px 24px;">
            <a href="{{report_url}}" style="display:inline-block;background:#6b4c9a;color:#ffffff;text-decoration:none;padding:12px 20px;border-radius:10px;font-weight:600;font-size:14px;">View full report</a>
            <p style="margin:14px 0 0;font-size:13px;color:#475569;">
              If you need anything added before a formal review (tax position, statements, exposure schedule), please reply to {{first_name}} directly — Oney is not holding a file for this client.
            </p>
          </td></tr>

          <tr><td style="padding:16px 28px 24px;border-top:1px solid #e5e7eb;">
            <p style="margin:0;font-size:11px;line-height:1.55;color:#64748b;">{{disclaimer}}</p>
          </td></tr>
        </table>
      </td></tr>
    </table>
  </body>
</html>`;

export const BROKER_TEXT = `Hi {{recipient_name}},

{{first_name}} has shared their Bank-Ready Score report with you for review.

Summary:
- Score: {{score}} / 100
- Readiness: {{score_band}}
- Recommended path: {{recommended_path}}

Business profile:
{{profile_summary}}

Top actions currently highlighted:
1. {{top_action_1}}
2. {{top_action_2}}
3. {{top_action_3}}

View the full report:
{{report_url}}

Important:
This client-shared report is a readiness signal based on user-provided information. It is not credit approval, not a credit decision, and not formal financial advice.`;
